# Generated by Django 6.0.3 on 2026-03-31 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoixReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, unique=True)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Choix de réponse',
                'verbose_name_plural': 'Choix de réponse',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rubrique',
                'verbose_name_plural': 'Rubriques',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_enfant', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField()),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'ordering': ['nom', 'prenom'],
                'constraints': [models.UniqueConstraint(fields=('nom', 'prenom', 'date_naissance'), name='unique_enfant_identite')],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('terminee', models.BooleanField(default=False)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interaction.enfant')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interaction.rubrique')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_min', models.PositiveIntegerField()),
                ('score_max', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='interaction.rubrique')),
            ],
            options={
                'verbose_name': 'Interprétation',
                'verbose_name_plural': 'Interprétations',
                'ordering': ['rubrique', 'score_min'],
            },
        ),
        migrations.CreateModel(
            name='ReponseParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_parents', to='interaction.choixreponse')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='interaction.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_parents', to='interaction.questionnaire')),
            ],
            options={
                'verbose_name': 'Réponse du parent',
                'verbose_name_plural': 'Réponses des parents',
                'constraints': [models.UniqueConstraint(fields=('evaluation', 'question'), name='unique_reponse_par_question')],
            },
        ),
    ]
