# Generated by Django 6.0.3 on 2026-03-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('score_min', models.PositiveIntegerField()),
                ('score_max', models.PositiveIntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Interprétation globale',
                'verbose_name_plural': 'Interprétations globales',
                'ordering': ['score_min'],
            },
        ),
        migrations.AlterModelOptions(
            name='interpretation',
            options={'ordering': ['rubrique', 'score_min'], 'verbose_name': 'Interprétation par rubrique', 'verbose_name_plural': 'Interprétations par rubrique'},
        ),
        migrations.RemoveField(
            model_name='reponseparent',
            name='choix',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='score_non',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='score_oui',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='score_parfois',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reponseparent',
            name='reponse',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non'), ('parfois', 'Parfois')], default='parfois', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponseparent',
            name='score_obtenu',
            field=models.IntegerField(default=0),
        ),
    ]
